### PR TITLE
add instructions to validate with atom.io editor

### PR DESCRIPTION
**Pull request by philschatz**
Moved from https://github.com/openstax/napkin-notes/pull/63

### CODE REVIEW

**Comment by philschatz** [comment]
yay, thanks for fixing 😄

**Comment by pumazi** [comment]
I don't know that this really belongs here, but I'll translate this to reStructuredText for you.

**Comment by pumazi** [comment]
@philschatz Everything look as you expected?

**Comment by philschatz** [comment]
yeppers!

**Pull request merged**
